In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"/content/Salary Prediction of Data Professions.csv")
df

,FIRST NAME,LAST NAME,SEX,DOJ,CURRENT DATE,DESIGNATION,AGE,SALARY,UNIT,LEAVES USED,LEAVES REMAINING,RATINGS,PAST EXP
0,TOMASA,ARMEN,F,5-18-2014,01-07-2016,Analyst,21.0,44570,Finance,24.0,6.0,2.0,0
1,ANNIE,NaN,F,NaN,01-07-2016,Associate,NaN,89207,Web,NaN,13.0,NaN,7
2,OLIVE,ANCY,F,7-28-2014,01-07-2016,Analyst,21.0,40955,Finance,23.0,7.0,3.0,0
3,CHERRY,AQUILAR,F,04-03-2013,01-07-2016,Analyst,22.0,45550,IT,22.0,8.0,3.0,0
4,LEON,ABOULAHOUD,M,11-20-2014,01-07-2016,Analyst,NaN,43161,Operations,27.0,3.0,NaN,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2634,KATHERINE,ALSDON,F,6-28-2011,01-07-2016,Senior Manager,36.0,185977,Management,15.0,15.0,5.0,10
2635,LOUISE,ALTARAS,F,1-14-2014,01-07-2016,Analyst,23.0,45758,IT,17.0,13.0,2.0,0
2636,RENEE,ALVINO,F,1-23-2014,01-07-2016,Analyst,21.0,47315,Web,29.0,1.0,5.0,0
2637,TERI,ANASTASIO,F,3-17-2014,01-07-2016,Analyst,24.0,45172,Web,23.0,7.0,3.0,1
2638,GREGORY,ABARCA,M,9-18-2014,01-07-2016,Analyst,24.0,49176,Marketing,17.0,13.0,2.0,2

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2639 entries, 0 to 2638
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   FIRST NAME        2639 non-null   object
 1   LAST NAME         2637 non-null   object
 2   SEX               2639 non-null   object
 3   DOJ               2638 non-null   object
 4   CURRENT DATE      2639 non-null   object
 5   DESIGNATION       2639 non-null   object
 6   AGE               2636 non-null   float64
 7   SALARY            2639 non-null   int64
 8   UNIT              2639 non-null   object
 9   LEAVES USED       2636 non-null   float64
 10  LEAVES REMAINING  2637 non-null   float64
 11  RATINGS           2637 non-null   float64
 12  PAST EXP          2639 non-null   int64
dtypes: float64(4), int64(2), object(7)
memory usage: 268.1+ KB

In [4]:
df.shape

(2639, 13)

In [6]:
#1)average salary of employee by designation
df.groupby("DESIGNATION")["SALARY"].mean()

DESIGNATION
Analyst            45020.111852
Associate          87202.981132
Director          286971.187500
Manager           126272.592593
Senior Analyst     59901.345506
Senior Manager    178664.274194
Name: SALARY, dtype: float64

In [8]:
#2)count of employees by department wise
df["DESIGNATION"].value_counts()

DESIGNATION
Analyst           1949
Senior Analyst     356
Associate          159
Manager             81
Senior Manager      62
Director            32
Name: count, dtype: int64

In [12]:
#3)who is the most experienced person
df.sort_values("PAST EXP",ascending=False).head(1).loc[:,["FIRST NAME","LAST NAME","DESIGNATION","PAST EXP"]]

    FIRST NAME LAST NAME DESIGNATION  PAST EXP
683    NUMBERS   AKIMSEU    Director        23

In [16]:
#4)top 5 rated employees
df.sort_values("RATINGS",ascending=False).head(5).loc[:,["FIRST NAME","LAST NAME","DESIGNATION","RATINGS"]]

     FIRST NAME LAST NAME     DESIGNATION  RATINGS
1320     ANTWAN   ALCARAZ       Associate      5.0
1075  KRISTOFER    ALLRED         Analyst      5.0
2372     BRYANT      ADIE        Director      5.0
991     EDUARDO     ACOBA  Senior Analyst      5.0
2370        LIZ      ARAN         Analyst      5.0

In [18]:
#5)who is the one who doesnt take leave
df[df['LEAVES USED'].isnull()]

,FIRST NAME,LAST NAME,SEX,DOJ,CURRENT DATE,DESIGNATION,AGE,SALARY,UNIT,LEAVES USED,LEAVES REMAINING,RATINGS,PAST EXP
1,ANNIE,NaN,F,NaN,01-07-2016,Associate,NaN,89207,Web,NaN,13.0,NaN,7
11,VIRGIL,ACKIES,M,02-01-2010,01-07-2016,Senior Manager,36.0,160613,Finance,NaN,11.0,2.0,9
19,PHILLIP,ABDULA,M,07-03-2013,01-07-2016,Analyst,24.0,44665,Web,NaN,12.0,5.0,0

In [19]:
#6 top most paid employee
df.sort_values("SALARY",ascending=False).head(1).loc[:,["FIRST NAME","LAST NAME","DESIGNATION","SALARY"]]

    FIRST NAME   LAST NAME DESIGNATION  SALARY
166      DEREK  ABOULISSAN    Director  388112

In [21]:
#7)find who is the fresher and belongs to which department
df[df["PAST EXP"]==0].loc[:,["FIRST NAME","LAST NAME","DESIGNATION","PAST EXP"]]

     FIRST NAME  LAST NAME DESIGNATION  PAST EXP
0        TOMASA      ARMEN     Analyst         0
2         OLIVE       ANCY     Analyst         0
3        CHERRY    AQUILAR     Analyst         0
5      VICTORIA        NaN     Analyst         0
6        ELLIOT     AGULAR     Analyst         0
...         ...        ...         ...       ...
2628       DREW      ADOLF     Analyst         0
2630      ELVIA  APPELGREN     Analyst         0
2632    MARLENE      AMAYA     Analyst         0
2635     LOUISE    ALTARAS     Analyst         0
2636      RENEE     ALVINO     Analyst         0

[1301 rows x 4 columns]

In [24]:
#8)who is the youngest employee working
df.sort_values("AGE",ascending= True).head(10)

,FIRST NAME,LAST NAME,SEX,DOJ,CURRENT DATE,DESIGNATION,AGE,SALARY,UNIT,LEAVES USED,LEAVES REMAINING,RATINGS,PAST EXP
0,TOMASA,ARMEN,F,5-18-2014,01-07-2016,Analyst,21.0,44570,Finance,24.0,6.0,2.0,0
362,RONALD,AARONSON,M,9-16-2013,01-07-2016,Analyst,21.0,44163,Finance,18.0,12.0,4.0,0
907,THERESA,ALSPACH,F,02-04-2014,01-07-2016,Analyst,21.0,44956,Web,28.0,2.0,2.0,0
1759,AUGUST,AGRICOLA,M,06-10-2013,01-07-2016,Analyst,21.0,43282,Finance,20.0,10.0,3.0,0
917,MOLLIE,ANGELORO,F,12-30-2013,01-07-2016,Analyst,21.0,47297,Management,21.0,9.0,5.0,0
919,SID,ALMAN,M,7-17-2014,01-07-2016,Analyst,21.0,45122,Finance,16.0,14.0,2.0,0
1755,HARRIET,AMICONE,F,11-26-2014,01-07-2016,Analyst,21.0,48751,Operations,15.0,15.0,4.0,0
348,ELBA,ARBOGAST,F,12-25-2014,01-07-2016,Analyst,21.0,47401,Finance,27.0,3.0,2.0,0
924,ERNA,ARAB,F,04-03-2014,01-07-2016,Analyst,21.0,40398,Operations,19.0,11.0,3.0,0
1752,LELA,ANDING,F,05-08-2014,01-07-2016,Analyst,21.0,42467,Marketing,21.0,9.0,3.0,0

In [40]:
#9)find the salary > 50k and exp > 5 in it field
df[df["UNIT"]== "IT"][(df["SALARY"]> 50000) & (df["PAST EXP"] > 5)].head(5)
#df[(df["SALARY"]> 50000) & (df["PAST EXP"] > 5)]

<ipython-input-40-8588322e3b91>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df["UNIT"]== "IT"][(df["SALARY"]> 50000) & (df["PAST EXP"] > 5)].head(5)

,FIRST NAME,LAST NAME,SEX,DOJ,CURRENT DATE,DESIGNATION,AGE,SALARY,UNIT,LEAVES USED,LEAVES REMAINING,RATINGS,PAST EXP,TENURE
46,JODY,ADOLFO,M,01-07-2015,01-07-2016,Associate,32.0,76411,IT,16.0,14.0,4.0,9,1.000000
164,BOOKER,AKRIGHT,M,10-14-2013,01-07-2016,Associate,32.0,83066,IT,23.0,7.0,4.0,6,2.232877
228,MICHEAL,ABLEMAN,M,4-20-2011,01-07-2016,Director,43.0,313649,IT,21.0,9.0,2.0,17,4.720548
247,SHARLENE,ARBUTHNOT,F,09-05-2014,01-07-2016,Senior Manager,39.0,191793,IT,20.0,10.0,3.0,17,1.339726
272,ANGELO,ADAMCIK,M,3-26-2014,01-07-2016,Manager,33.0,140867,IT,27.0,3.0,4.0,7,1.786301

In [39]:
#10)AVERAGE LEAVES REMAINING BY DESIGNATION
df.groupby("DESIGNATION")["LEAVES REMAINING"].mean()

DESIGNATION
Analyst           7.547509
Associate         6.955975
Director          6.968750
Manager           7.123457
Senior Analyst    7.522472
Senior Manager    8.177419
Name: LEAVES REMAINING, dtype: float64